// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsWAcYj1w80_9lYFFSwwvRlcVmq9W1LYk',
    appId: '1:810811293051:web:14dca820b42bae9ee9d1de',
    messagingSenderId: '810811293051',
    projectId: 'year-in-pixels-e3544',
    authDomain: 'year-in-pixels-e3544.firebaseapp.com',
    storageBucket: 'year-in-pixels-e3544.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH-xFw238WrkrKJJxSpTEetddzznqAuE0',
    appId: '1:810811293051:android:99efd00822415877e9d1de',
    messagingSenderId: '810811293051',
    projectId: 'year-in-pixels-e3544',
    storageBucket: 'year-in-pixels-e3544.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0QwwS5f_wk9Wxr1r-5xVhLBX8cu-33XE',
    appId: '1:810811293051:ios:70e77bcde025f1e0e9d1de',
    messagingSenderId: '810811293051',
    projectId: 'year-in-pixels-e3544',
    storageBucket: 'year-in-pixels-e3544.appspot.com',
    iosBundleId: 'com.example.yearInPixels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0QwwS5f_wk9Wxr1r-5xVhLBX8cu-33XE',
    appId: '1:810811293051:ios:70e77bcde025f1e0e9d1de',
    messagingSenderId: '810811293051',
    projectId: 'year-in-pixels-e3544',
    storageBucket: 'year-in-pixels-e3544.appspot.com',
    iosBundleId: 'com.example.yearInPixels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsWAcYj1w80_9lYFFSwwvRlcVmq9W1LYk',
    appId: '1:810811293051:web:56dab8b0aeb11e12e9d1de',
    messagingSenderId: '810811293051',
    projectId: 'year-in-pixels-e3544',
    authDomain: 'year-in-pixels-e3544.firebaseapp.com',
    storageBucket: 'year-in-pixels-e3544.appspot.com',
  );
}
